DROP TABLE  emp_new;
DROP TABLE dept_new;
CREATE TABLE emp_new AS SELECT * FROM EMP;
CREATE TABLE dept_new AS SELECT * FROM DEPT;
ALTER TABLE dept_new ADD CONSTRAINT dept_noPri PRIMARY KEY(DEPTNO);
ALTER TABLE emp_new ADD Grade CHAR(1);
ALTER TABLE emp_new ADD CONSTRAINT emp_noPri PRIMARY KEY(EMPNO);
ALTER TABLE emp_new MODIFY DEPTNO REFERENCES dept_new(DEPTNO);
UPDATE emp_new SET SAL=SAL WHERE(SAL>2500);
ALTER TABLE emp_new MODIFY(SAL NUMBER(10,2) NOT NULL);
ALTER TABLE emp_new MODIFY(ENAME VARCHAR2(35));
ALTER TABLE emp_new DROP PRIMARY KEY;

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'EMP_NEW';
ALTER TABLE emp_new DROP CONSTRAINT SYS_C008235;
ALTER TABLE dept_new DISABLE CONSTRAINT dept_noPri;
ALTER TABLE dept_new drop PRIMARY key cascade;

CREATE TABLE EMP_NEW1 AS SELECT * FROM EMP;
CREATE TABLE DEPT_NEW1 AS SELECT * FROM DEPT;
ALTER TABLE DEPT_NEW1 ADD PRIMARY KEY(DEPTNO);
ALTER TABLE EMP_NEW1 MODIFY DEPTNO REFERENCES DEPT_NEW1(DEPTNO);
DROP TABLE DEPT_NEW1;

COMMENT ON TABLE emp IS 'Employee Information of XYZ Company'; 
COMMENT ON COLUMN dept.deptno is 'Unique depart of XYZ Company';
select TABLE_NAME,COMMENTS,COLUMN_NAME from USER_COL_COMMENTS where TABLE_NAME LIKE 'DEPT' and COLUMN_NAME LIKE 'DEPTNO';
select TABLE_NAME,COMMENTS from USER_TAB_COMMENTS where TABLE_NAME = 'EMP';
COMMENT ON TABLE emp IS '';
RENAME EMP TO EMP_CHANGE;
TRUNCATE TABLE EMP_NEW1;
DROP TABLE DEPT_NEW1 CASCADE CONSTRAINTS;
ALTER TABLE EMP_NEW DROP COLUMN Grade;
ALTER TABLE EMP_NEW RENAME COLUMN COMM to COMMISSION;
ALTER TABLE EMP_NEW SET UNUSED COLUMN COMMISSION;
DESC USER_UNUSED_COL_TABS;
select TABLE_NAME , COUNT from USER_UNUSED_COL_TABS where TABLE_NAME like 'EMP_NEW';
ALTER TABLE EMP_NEW DROP UNUSED COLUMNS;